/**
 * IMPACTMESH - Groq Service Abstraction (Server-Side Only)
 * Handles structured evidence prompts and strategic reasoning queries to the Groq API.
 * Strict Architecture Rule:
 * 1. Groq is strictly isolated to the server.
 * 2. Groq is NEVER the source of truth for numbers or metrics.
 * 3. Groq receives ONLY pre-calculated deterministic evidence, never direct database access.
 */

import type { StructuredReasoningEvidence, ReasoningResult } from '../types/server-types.ts';
import type { ExecutiveRole } from '../../src/types/policies.ts';

export interface GroqServiceConfig {
  apiKey?: string;
  model?: string;
  temperature?: number;
}

export class GroqService {
  private apiKey: string;
  private model: string;
  private temperature: number;

  constructor(config?: GroqServiceConfig) {
    // Process environment variable strictly server-side
    this.apiKey = config?.apiKey || (typeof process !== 'undefined' ? process.env.GROQ_API_KEY || '' : '');
    this.model = config?.model || 'llama-3.3-70b-versatile';
    this.temperature = config?.temperature ?? 0.2;
  }

  /**
   * Checks whether the Groq API key is configured.
   */
  public isConfigured(): boolean {
    return Boolean(this.apiKey) && !this.apiKey.includes('placeholder');
  }

  /**
   * Formats structured evidence into an explicit, deterministic prompt
   * instructing the LLM to explain and strategically reason over provided evidence.
   */
  public constructEvidencePrompt(
    evidence: StructuredReasoningEvidence,
    perspective: ExecutiveRole
  ): { systemPrompt: string; userPrompt: string } {
    const systemPrompt = `You are the Strategic Reasoning Layer of IMPACTMESH for Blacktide Systems.
Your role is to analyze deterministic facts, graph dependencies, and pre-calculated impact metrics to explain trade-offs and provide executive-level strategic rationale.

RULES:
1. You DO NOT calculate or fabricate financial numbers, capacity, or risk scores. Use ONLY the metrics provided in the evidence.
2. Evaluate decisions strictly through the lens of the requested executive perspective: ${perspective.toUpperCase()}.
3. Synthesize why particular options align or conflict with executive priorities.
4. Provide structured, concise rationale and concrete mitigation steps.`;

    const userPrompt = `EVIDENCE DOSSIER:
- Organization: Blacktide Systems (${evidence.organizationId})
- Triggering Event: [${evidence.triggeringEvent.department.toUpperCase()}] ${evidence.triggeringEvent.event_type}
- Event Payload: ${JSON.stringify(evidence.triggeringEvent.payload, null, 2)}

CURRENT BUSINESS STATE:
- Available Budget: ₹${evidence.currentBusinessState.metrics.available_budget.toLocaleString('en-US')}
- Committed Budget: ₹${evidence.currentBusinessState.metrics.committed_budget.toLocaleString('en-US')}
- Pipeline Revenue: ₹${evidence.currentBusinessState.metrics.revenue_pipeline.toLocaleString('en-US')}
- Engineering Capacity: ${evidence.currentBusinessState.metrics.engineering_capacity} hrs/wk
- Engineering Utilization: ${evidence.currentBusinessState.metrics.capacity_utilization}%
- Budget Pressure: ${evidence.currentBusinessState.metrics.budget_pressure}
- Overall Risk Score: ${evidence.currentBusinessState.metrics.risk_score}

DETERMINISTIC IMPACT & CASCADE:
- Cascade Depth: ${evidence.deterministicImpact.cascade_depth} hops
- Affected Entities: ${evidence.affectedEntities.map((e) => `${e.entity.name} (${e.impactSeverity})`).join(', ')}
- Metric Deltas: ${JSON.stringify(evidence.deterministicImpact.metric_deltas)}
- Primary Bottlenecks: ${evidence.deterministicImpact.risk_assessment.bottlenecks.join(', ')}

DECISION CANDIDATES GENERATED BY ENGINE:
${evidence.generatedOptions
  .map(
    (opt, i) => `[Option ${i + 1}: ${opt.id}] ${opt.title}
Action: ${opt.action_type}
Feasibility: ${opt.feasibility_score}/100
Policy Alignments: CEO=${opt.policy_alignment.ceo}, CFO=${opt.policy_alignment.cfo}, COO=${opt.policy_alignment.coo}
Pros: ${opt.tradeoffs.pros.join('; ')}
Cons: ${opt.tradeoffs.cons.join('; ')}`
  )
  .join('\n\n')}

Analyze this evidence and provide strategic synthesis and recommended course of action.`;

    return { systemPrompt, userPrompt };
  }

  /**
   * Executes strategic reasoning query against Groq API.
   * In Phase 1, if API key is not set, returns a structured dry-run simulation
   * based on the deterministic evidence.
   */
  public async executeReasoning(
    evidence: StructuredReasoningEvidence,
    perspective: ExecutiveRole = 'balanced'
  ): Promise<ReasoningResult> {
    const startTime = Date.now();
    const { systemPrompt, userPrompt } = this.constructEvidencePrompt(evidence, perspective);

    // If Groq API key is present and configured, call the live Groq endpoint
    if (this.isConfigured()) {
      try {
        const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
          method: 'POST',
          headers: {
            Authorization: `Bearer ${this.apiKey}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            model: this.model,
            messages: [
              { role: 'system', content: systemPrompt },
              { role: 'user', content: userPrompt },
            ],
            temperature: this.temperature,
            response_format: { type: 'json_object' },
          }),
        });

        if (response.ok) {
          const data = (await response.json()) as {
            choices: Array<{ message: { content: string } }>;
            usage?: { total_tokens: number };
          };
          const content = data.choices[0]?.message?.content || '{}';
          const parsed = JSON.parse(content) as Record<string, unknown>;

          return {
            recommendedOptionId:
              (parsed.recommendedOptionId as string) ||
              evidence.generatedOptions[0]?.id ||
              'opt-fallback',
            perspective,
            synthesis: {
              executive_summary:
                (parsed.executive_summary as string) ||
                'Reasoning completed based on deterministic evidence.',
              strategic_rationale:
                (parsed.strategic_rationale as string) ||
                'Strategic alignment verified against executive policy priorities.',
              tradeoff_assessment:
                (parsed.tradeoff_assessment as string) ||
                'Balances operational capacity against commercial commitments.',
              counterfactual_analysis:
                (parsed.counterfactual_analysis as string) ||
                'Rejecting this commitment avoids risk but foregoes pipeline acceleration.',
              risk_mitigations: (parsed.risk_mitigations as string[]) || [
                'Establish weekly milestone checkpoints',
                'Monitor team burn rate',
              ],
            },
            policyAlignmentScores: {
              ceo: evidence.generatedOptions[0]?.policy_alignment.ceo || 75,
              cfo: evidence.generatedOptions[0]?.policy_alignment.cfo || 70,
              coo: evidence.generatedOptions[0]?.policy_alignment.coo || 65,
              balanced: evidence.generatedOptions[0]?.policy_alignment.balanced || 70,
            },
            confidenceScore: 0.92,
            tokensUsed: data.usage?.total_tokens,
            executionTimeMs: Date.now() - startTime,
          };
        }
      } catch (err) {
        console.warn(
          '[GroqService] Live call failed, falling back to structured evidence synthesis:',
          err
        );
      }
    }

    // Structured architectural dry-run response (Phase 1 boundary)
    const topOption = evidence.generatedOptions[0];
    return {
      recommendedOptionId: topOption ? topOption.id : 'opt-default',
      perspective,
      synthesis: {
        executive_summary: `[Phase 1 Synthesis] Evaluation for ${evidence.triggeringEvent.event_type} through ${perspective.toUpperCase()} policy lens.`,
        strategic_rationale: topOption?.rationale || topOption?.description || 'Deterministic evaluation shows sustainable path with proactive scope management.',
        tradeoff_assessment: `Identified ${evidence.affectedEntities.length} affected entities across ${evidence.deterministicImpact.cascade_depth} dependency tiers.`,
        counterfactual_analysis:
          'Failing to resolve this dependency creates a cascading delivery delay across dependent customer commitments.',
        risk_mitigations: evidence.deterministicImpact.risk_assessment.primary_risks.map(
          (r) => `Mitigation: ${r}`
        ),
      },
      policyAlignmentScores: topOption
        ? topOption.policy_alignment
        : { ceo: 75, cfo: 70, coo: 65, balanced: 70 },
      confidenceScore: 0.88,
      executionTimeMs: Date.now() - startTime,
    };
  }
}

export const groqService = new GroqService();
